language: java
sudo: false
addons:
  postgresql: 9.6

  apt:
    packages:
      - oracle-java8-installer
      - postgresql-9.6
jdk:
  - oraclejdk8
before_script:
  - psql -c 'create database bookstore;' -U postgres
  - psql -c "alter user postgres with password 'sqlpq';"
